"""KML export for VoronoiMap — generates Google Earth KML files.

Exports Voronoi regions as KML Polygons and optionally seed points as
KML Placemarks, viewable in Google Earth, Google Maps, and other KML
consumers.
"""

import xml.etree.ElementTree as ET
from xml.dom import minidom

import vormap


# Six color schemes matching vormap_viz SVG palettes (AABBGGRR for KML)
_KML_COLORS = {
    'pastel': [
        '7fd5e0ff', '7fffb3b3', '7fb3ffb3', '7fb3d9ff',
        '7fff99ff', '7f99ffff', '7fffff99', '7fffcc99',
    ],
    'warm': [
        '7f4040ff', '7f4080ff', '7f4040ff', '7f00a5ff',
        '7f0080ff', '7f0000ff', '7f00d7ff', '7f00ffff',
    ],
    'cool': [
        '7fffff00', '7fffcc00', '7fff9900', '7fff6600',
        '7fff3300', '7fff0000', '7fcc0000', '7f990000',
    ],
    'earth': [
        '7f8cb4d2', '7f80c0a0', '7f90d0b0', '7fa0d8c0',
        '7fb0e0d0', '7fc0e8e0', '7fd0f0f0', '7fe0f8f8',
    ],
    'mono': [
        '7fffffff', '7fe0e0e0', '7fc0c0c0', '7fa0a0a0',
        '7f808080', '7f606060', '7f404040', '7f202020',
    ],
    'rainbow': [
        '7f0000ff', '7f00a5ff', '7f00ffff', '7f00ff00',
        '7fffff00', '7fffcc00', '7fff0000', '7fff00ff',
    ],
}


from vormap_geometry import (
    build_data_index as _build_data_index,
    polygon_area as _compute_region_area,
)


def export_kml(
    regions,
    data,
    output_path,
    *,
    include_seeds=True,
    color_scheme='pastel',
    region_names_fn=None,
):
    """Export Voronoi regions as a KML file for Google Earth.

    Parameters
    ----------
    regions : dict
        Output of ``compute_regions()`` — maps seed → vertex list.
    data : list of (float, float)
        All seed points.
    output_path : str
        Path to write the KML file.
    include_seeds : bool
        If True (default), include seed points as Placemarks.
    color_scheme : str
        Color scheme name (pastel, warm, cool, earth, mono, rainbow).
    region_names_fn : callable or None
        Optional ``(seed, vertices, index) → str`` for custom names.

    Returns
    -------
    str
        Path to the generated KML file.
    """
    if not regions:
        raise ValueError("No regions to export")

    colors = _KML_COLORS.get(color_scheme, _KML_COLORS['pastel'])
    sorted_seeds = sorted(regions.keys())
    data_lookup = _build_data_index(data)

    # Build KML document
    kml = ET.Element('kml', xmlns='http://www.opengis.net/kml/2.2')
    doc = ET.SubElement(kml, 'Document')
    ET.SubElement(doc, 'name').text = 'VoronoiMap Diagram'
    ET.SubElement(doc, 'description').text = (
        'Voronoi tessellation generated by VoronoiMap'
    )

    # Create styles for each color
    for i, color in enumerate(colors):
        style = ET.SubElement(doc, 'Style', id='style%d' % i)
        line_style = ET.SubElement(style, 'LineStyle')
        ET.SubElement(line_style, 'color').text = 'ff000000'
        ET.SubElement(line_style, 'width').text = '1'
        poly_style = ET.SubElement(style, 'PolyStyle')
        ET.SubElement(poly_style, 'color').text = color

    # Seed point style
    seed_style = ET.SubElement(doc, 'Style', id='seedStyle')
    icon_style = ET.SubElement(seed_style, 'IconStyle')
    ET.SubElement(icon_style, 'color').text = 'ff0000ff'
    ET.SubElement(icon_style, 'scale').text = '0.6'
    icon = ET.SubElement(icon_style, 'Icon')
    ET.SubElement(icon, 'href').text = (
        'http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png'
    )

    # Regions folder
    regions_folder = ET.SubElement(doc, 'Folder')
    ET.SubElement(regions_folder, 'name').text = 'Voronoi Regions'

    for idx, seed in enumerate(sorted_seeds):
        verts = regions[seed]
        data_idx = data_lookup.get(tuple(seed), idx)
        area = _compute_region_area(verts)

        if region_names_fn:
            name = region_names_fn(seed, verts, data_idx)
        else:
            name = 'Region %d' % (data_idx + 1)

        pm = ET.SubElement(regions_folder, 'Placemark')
        ET.SubElement(pm, 'name').text = name
        ET.SubElement(pm, 'description').text = (
            'Seed: (%.4f, %.4f)\nArea: %.4f\nVertices: %d'
            % (seed[0], seed[1], area, len(verts))
        )
        ET.SubElement(pm, 'styleUrl').text = (
            '#style%d' % (idx % len(colors))
        )

        polygon = ET.SubElement(pm, 'Polygon')
        ET.SubElement(polygon, 'altitudeMode').text = 'clampToGround'
        outer = ET.SubElement(polygon, 'outerBoundaryIs')
        ring = ET.SubElement(outer, 'LinearRing')

        # Build coordinate string (lng,lat,alt)
        coords = []
        for v in verts:
            coords.append('%.6f,%.6f,0' % (v[0], v[1]))
        # Close the ring
        if verts:
            coords.append('%.6f,%.6f,0' % (verts[0][0], verts[0][1]))
        ET.SubElement(ring, 'coordinates').text = ' '.join(coords)

    # Seeds folder
    if include_seeds:
        seeds_folder = ET.SubElement(doc, 'Folder')
        ET.SubElement(seeds_folder, 'name').text = 'Seed Points'

        for idx, (px, py) in enumerate(data):
            pm = ET.SubElement(seeds_folder, 'Placemark')
            ET.SubElement(pm, 'name').text = 'Seed %d' % (idx + 1)
            ET.SubElement(pm, 'description').text = (
                'Point %d at (%.4f, %.4f)' % (idx + 1, px, py)
            )
            ET.SubElement(pm, 'styleUrl').text = '#seedStyle'
            point = ET.SubElement(pm, 'Point')
            ET.SubElement(point, 'coordinates').text = (
                '%.6f,%.6f,0' % (px, py)
            )

    # Pretty-print and write
    rough_string = ET.tostring(kml, encoding='unicode')
    reparsed = minidom.parseString(rough_string)
    pretty_xml = reparsed.toprettyxml(indent='  ', encoding=None)
    # Remove extra XML declaration if present
    lines = pretty_xml.split('\n')
    if lines and lines[0].startswith('<?xml'):
        lines[0] = '<?xml version="1.0" encoding="UTF-8"?>'

    output_path = vormap.validate_output_path(output_path, allow_absolute=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    return output_path


def generate_kml(
    datafile,
    output_path='voronoi.kml',
    *,
    include_seeds=True,
    color_scheme='pastel',
):
    """Load data, compute regions, and export KML in one call.

    Parameters
    ----------
    datafile : str
        Filename inside the data/ directory.
    output_path : str
        Where to write the KML file.
    include_seeds : bool
        Include seed points as Placemarks.
    color_scheme : str
        Color scheme for region fills.

    Returns
    -------
    str
        Path to the generated KML file.
    """
    import vormap_viz

    data = vormap.load_data(datafile)
    regions = vormap_viz.compute_regions(data)
    return export_kml(
        regions,
        data,
        output_path,
        include_seeds=include_seeds,
        color_scheme=color_scheme,
    )
